parameters:
#    smartdiary_security.example.class: Smartdiary\Bundle\SecurityBundle\Example

services:
#    smartdiary_security.example:
#        class: %smartdiary_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
