parameters:
#    smartdiary_consequence.example.class: Smartdiary\ConsequenceBundle\Example

services:
    smartdiary_consequence.form.type.emotion_detail:
            class: Smartdiary\ConsequenceBundle\Form\Type\EmotionDetailType
            tags:
                - { name: form.type, alias: emotion_detail }

    smartdiary_consequence.create_emotion_form_handler:
        class: Smartdiary\ConsequenceBundle\Form\Handler\CreateEmotionFormHandler
