parameters:
#    smartdiary_consequence.example.class: Smartdiary\ConsequenceBundle\Example

services:
#    smartdiary_consequence.example:
#        class: %smartdiary_consequence.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
