home:
    path: /
    defaults:  { _controller: SmartdiarySmartdiaryBundle:Smartdiary:home }
login:
    path:   /login
    defaults:  { _controller: SmartdiarySecurityBundle:Security:login }
logout:
    path: /logout
login_check:
    path:   /login_check

SmartdiaryAlternativePositiveThought:
    resource: "@SmartdiaryAlternativePositiveThoughtBundle/Resources/config/routing.yml"
    prefix:   /

SmartdiaryAntecedentBundle:
    resource: "@SmartdiaryAntecedentBundle/Resources/config/routing.yml"
    prefix:   /

SmartdiaryAutomaticNegativeThoughtBundle:
    resource: "@SmartdiaryAutomaticNegativeThoughtBundle/Resources/config/routing.yml"
    prefix:   /

SmartdiaryBehaviorBundle:
    resource: "@SmartdiaryBehaviorBundle/Resources/config/routing.yml"
    prefix:   /

SmartdiaryConsequenceBundle:
    resource: "@SmartdiaryConsequenceBundle/Resources/config/routing.yml"
    prefix:   /

SmartdiaryEmotionRevaluation:
    resource: "@SmartdiaryEmotionRevaluationBundle/Resources/config/routing.yml"
    prefix:   /

SmartdiarySmartdiaryBundle:
    resource: "@SmartdiarySmartdiaryBundle/Resources/config/routing.yml"
    prefix:   /

SmartdiaryUserBundle:
    resource: "@SmartdiaryUserBundle/Resources/config/routing.yml"