security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Smartdiary\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    user:  { password: user, roles: [ 'ROLE_USER' ] }
                    admin: { password: admin, roles: [ 'ROLE_TEACHER' ] }
        user_db:
            entity: { class: Smartdiary\UserBundle\Entity\User, property: username }
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        home:
            pattern: ^/smartdiary/home
            anonymous: ~
        index:
            pattern: ^/
            anonymous: ~
        login:
            pattern:  ^/login$
            anonymous: ~
        user_new:
            pattern:  ^/utente/nuovo$
            anonymous: ~
        secured_area:
            pattern:    ^/
            form_login:
                check_path: login_check
                login_path: login
                always_use_default_target_path: true
                default_target_path: smartdiary_smartdiary_smartdiary_index
            remember_me:
                key: "%secret%"
                lifetime: 604800
                path:     /
                domain:   ~
            logout:
                path:   logout
                target: smartdiary_smartdiary_smartdiary_home
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/smartdiary/insegnante/*, roles: ROLE_TEACHER }
        - { path: ^/smartdiary/studente/*, roles: ROLE_STUDENT }