parameters:

services:
    smartdiary_user.create_account_form_handler:
        class: Smartdiary\UserBundle\Form\Handler\CreateUserFormHandler
        arguments: [@doctrine.orm.entity_manager, @security.encoder_factory, @session]

    smartdiary_user.form.type.user:
        class: Smartdiary\UserBundle\Form\Type\UserType
        tags:
            - { name: form.type, alias: user }

    smartdiary_user.validator.teacher_email:
        class: Smartdiary\UserBundle\Validator\Constraints\TeacherEmailValidator
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: validator.constraint_validator, alias: teacher_email }